package com.github.j5ik2o.reactive.redis.feature

import com.github.j5ik2o.reactive.redis.RedisClient

trait ClusterFeature { this: RedisClient =>
  /**
  * CLUSTER ADDSLOTS
  * CLUSTER COUNT-FAILURE-REPORTS
  * CLUSTER COUNTKEYSINSLOT
  * CLUSTER DELSLOTS
  * CLUSTER FAILOVER
  * CLUSTER FORGET
  * CLUSTER GETKEYSINSLOT
  * CLUSTER INFO
  * CLUSTER KEYSLOT
  * CLUSTER MEET
  * CLUSTER NODES
  * CLUSTER REPLICATE
  * CLUSTER RESET
  * CLUSTER SAVECONFIG
  * CLUSTER SET-CONFIG-EPOCH
  * CLUSTER SETSLOT
  * CLUSTER SLAVES
  * CLUSTER SLOTS
  * READONLY
  * READWRITE
  */
}
