version: 2
jobs:
  build:
    environment:
      - JAVA_OPTS: "-XX:ReservedCodeCacheSize=256M -Xms1g -Xmx3g -Xss2m"
    branches:
      only:
        - /feature\/.*/
    machine: true
    steps:
      - run:
          command: |
            sudo apt-get update -qq && sudo apt-get install -y libaio1 libevent-dev
            sudo apt-get install -y software-properties-common
            sudo add-apt-repository -y ppa:webupd8team/java
            sudo apt-get update -qq
            echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | sudo /usr/bin/debconf-set-selections
            sudo apt-get install -y oracle-java8-installer
            sudo apt-get install -y sbt
      - checkout
      - restore_cache:
          key: scala-library-dependencies-{{ checksum "build.sbt" }}
      - run: sbt +core/test:compile && sbt +pool-commons/test:compile && sbt +pool-fop/test:compile && sbt +pool-scala/test:compile && sbt +pool-stormpot/test:compile
      - save_cache:
          paths: [ "~/.sbt/boot", "~/.ivy2", "~/.wixMySQL" ]
          key: scala-library-dependencies-{{ checksum "build.sbt" }}
      - run: sbt +core/test && sbt +pool-commons/test && sbt +pool-fop/test && sbt +pool-scala/test && sbt +pool-stormpot/test
