# Scala CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/sample-config/ for more details
#
version: 2
jobs:
  build:
    branches:
      ignore:
        - master
        - develop
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    environment:
      SBT_OPTS: -Xss2m -Xms1g -Xmx3g -XX:MaxMetaspaceSize=512m
      TERM: dumb

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.sbt" }}
      - run:  sbt +core/test:compile && sbt +pool-commons/test:compile && sbt +pool-fop/test:compile && sbt +pool-scala/test:compile && sbt +pool-stormpot/test:compile

      - save_cache:
          paths:
            - "~/.ivy2/cache"
            - "~/.sbt"
          key: v1-dependencies--{{ checksum "build.sbt" }}

      - run: sbt clean coverage
      - run: sbt +core/test
      - run: sbt +pool-commons/test
      - run: sbt +pool-fop/test
      - run: sbt +pool-scala/test
      - run: sbt +pool-stormpot/test
      - run: sbt coverageReport coverageAggregate
      - run: sbt coveralls
